name: Build Binary

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    paths:
      - "**.ino"
  workflow_dispatch:
    inputs:
      ver:
        description: Build version
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_ver
        run: |
          if [[ -n "${{ github.event.inputs.ver }}" ]]; then
            VER="${{ github.event.inputs.ver }}"
          elif [[ $GITHUB_REF == "refs/tags/"* ]]; then
            VER="v${GITHUB_REF/refs\/tags\//}"
          else
            VER="main(${GITHUB_SHA:0:7})"
          fi
          echo "ver=$VER" >> $GITHUB_OUTPUT

      - name: Replace version string
        run: |
          sed -i "s/#define VERSION \".*\"/#define VERSION \"${{ steps.get_ver.outputs.ver }}\"/" cubefx/cubefx.ino

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install Arduino Core for ESP32
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32 --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install "ArduinoJson" "OneButton" "WS2812FX"

      - name: Compile Sketch
        run: |
          mkdir -p build
          arduino-cli compile --fqbn esp32:esp32:esp32c3 ./cubefx --output-dir ./build

      - name: Archive Binary
        run: |
          cp ./build/cubefx.ino.bin CubeFX_${{ steps.get_ver.outputs.ver }}.bin

      - name: Save to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ steps.get_ver.outputs.ver }}
          path: ./build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: false
          generate_release_notes: true
          files: |
            CubeFX_${{ steps.get_ver.outputs.ver }}.bin
